name: RelicsHunter
version: '${project.version}'
main: com.mastergap.relicshunter.Relicshunter
api-version: 1.19

commands:
  structurescan:
    description: test
    usage: /structurescan <b1x> <b1y> <b1z> <b2x> <b2y> <b2z>

  structureload:
    description: test
    usage: /structureload <sx> <sy> <sz> <structurename>

  generatedungeon:
    description: generates dungeon
    usage: /generatedungeon <sx> <sy> <sz> <roomcount>

  summonrelic:
    description: test
    usage: /summonrelic <relicname>

  spawnseller:
    description: test
    usage: /spawnseller

  spawnreturn:
    description: test
    usage: /spawnreturn

  spawnsurface:
    description: test
    usage: /spawnsurface

  starthunt:
    description: test
    usage: /starthunt

  endhunt:
    description: test
    usage: /endhunt